### PR TITLE
Represent timestamps as datetime objects

### PR DESCRIPTION
**Pull request by JacobHenner**
Resolves the `TODO` in alert.py, adds datetime support to _ts_parse()

### CODE REVIEW

**Comment by zebpalmer** [comment]
Thanks for PR, I'll happily merge this, but it's failing builds in 2.7.  fix that and I'll merge.  

ValueError: 'z' is a bad directive in format '%Y-%m-%dT%H:%M:%S%z'
 

also, this hasn't been touched in ages, I'm amazed it works.

**Comment by JacobHenner** [comment]
Sounds good, I'll try to fix sometime tomorrow. Thanks!

**Comment by JacobHenner** [comment]
Fixed to accommodate both Python 2 and Python 3. datetime objects are set as UTC.

**Comment by JacobHenner** [comment]
This should be good, now.

**Comment by JacobHenner** [comment]
Would still love to see this merged in if you're interested :smiley:

**Pull request merged**
